### ISSUE TITLE
files modified during buildbarn remote execution?

### ISSUE THREAD

**Issue by Ryang20718** [buildbarn/bb-deployments#162]
Hi 😄 

I'm attempting to test out buildbarn and am running into this weird non-deterministic issue where null bytes & files copied over into the worker contain different contents than the actual source.

I.e we have a python file imported as a transitive dependency

bazel client
```
cat bazel-external/pip_antlr4_python3_runtime/site-packages/antlr4/error/__init__.py
__author__ = 'ericvergnaud'
```

However, during remote execution, I'm seeing
```
  File "/worker/build/807/root/bazel-out/k8-opt/bin/test/data_tests.runfiles/pip_antlr4_python3_runtime/site-packages/antlr4/BufferedTokenStream.py", line 18, in <module>
    from antlr4.error.Errors import IllegalStateException
  File "/worker/build/807/root/bazel-out/k8-opt/bin/test/data/data_tests.runfiles/pip_antlr4_python3_runtime/site-packages/antlr4/error/__init__.py", line 1
    ����F����$#��T*�i��.t�i%�L
           ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x9a in position 0: invalid start byte
Action details (uncached result): https://buildbarn-browser.sandbox-dev.test.net/fuse/blobs/sha256/historical_execute_response/f4bc78e331eb87c71e78f6340b4fa6a5113eadd8c01cc8019d62e46c96981c43-1042/
````

Shelling into the instance during execution and catting out the contents of the file, I see
```
root@worker-ubuntu22-04-5f9d7cb958-whsx4:/home/github_actions# cat /worker/build/*/root/bazel-out/k8-opt/bin/waabi/map/*/*/*/pip_antlr4_python3_runtime/site-packages/antlr4/error/__init__.py
���F����$#��T*�i��.t�i%�L
```

Debugging details

We're using a kubernetes deployment and we have 2 storage + 2 worker nodes each which serves 1 pod (for testing) and other misc network nodes

<details>

<summary>worker config</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ubuntu22-04
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      instance: ubuntu22-04
  template:
    metadata:
      labels:
        app: worker
        instance: ubuntu22-04
    spec:
      containers:
      - name: worker
        resources:
          limits:
            cpu: "1"
            memory: 1500Mi
          requests:
            cpu: "0.5"
            memory: 1200Mi
        args:
        - /config/worker-ubuntu22-04.jsonnet
        image: ghcr.io/buildbarn/bb-worker:20241215T094620Z-d03d5e3
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /worker
          mountPropagation: Bidirectional
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        - mountPath: /storage-worker-fsac
          name: storage-worker-fsac
        - mountPath: "/var/run/docker.sock"
          name: dockersock
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: runner
        resources:
          limits:
            cpu: "7"
            memory: 27Gi
          requests:
            cpu: "6"
            memory: 26Gi
        command: [/bb/tini, -v, --, /bb/bb_runner, /config/runner-ubuntu22-04.jsonnet]
        image: <image>
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /worker
          mountPropagation: HostToContainer
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        - mountPath: /storage-worker-fsac
          name: storage-worker-fsac
        - mountPath: /dev/shm
          name: shared-memory
        - mountPath: /bb
          name: empty
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: dockersock
        securityContext:
          privileged: true
          runAsUser: 0
      initContainers:
      - name: bb-runner-installer
        image: ghcr.io/buildbarn/bb-runner-installer:20241215T094620Z-d03d5e3
        volumeMounts:
        - mountPath: /bb/
          name: empty
      - name: volume-init
        image: busybox:1.31.1-uclibc
        command:
        - sh
        - -c
        - mkdir -pm 0777 /worker/build && mkdir -pm 0700 /worker/cache && mkdir -pm 0777 /storage-worker-cas && mkdir -pm 0777 /storage-worker-fsac && chmod 0777 /worker
        volumeMounts:
        - mountPath: /worker
          name: worker
        - mountPath: /storage-worker-cas
          name: storage-worker-cas
        - mountPath: /storage-worker-fsac
          name: storage-worker-fsac
      volumes:
      - name: empty
        hostPath:
          path: /mnt/fast-disks/kube
      - name: configs
        configMap:
          name: buildbarn-config
          items:
          - key: common.libsonnet
            path: common.libsonnet
          - key: runner-ubuntu22-04.jsonnet
            path: runner-ubuntu22-04.jsonnet
          - key: worker-ubuntu22-04.jsonnet
            path: worker-ubuntu22-04.jsonnet
      - name: worker
        hostPath:
          path: /mnt/fast-disks/kube
      - name: storage-worker-cas
        hostPath:
          path: /mnt/fast-disks/kube
      - name: storage-worker-fsac
        hostPath:
          path: /mnt/fast-disks/kube
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: shared-memory
        hostPath:
          path: /dev/shm
```

```
local common = import 'common.libsonnet';
{
    blobstore: {
    actionCache: common.blobstore.actionCache,
    contentAddressableStorage: {
        readCaching: {
        slow: common.blobstore.contentAddressableStorage,
        fast: {
            'local': {
            keyLocationMapOnBlockDevice: {
            file: {
                path: '/storage-worker-cas/key_location_map',
                sizeBytes: 100 * 1024 * 1024,
            },
            },
            keyLocationMapMaximumGetAttempts: 8,
            keyLocationMapMaximumPutAttempts: 32,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
                source: {
                file: {
                path: '/storage-worker-cas/blocks',
                sizeBytes: 350 * 1024 * 1024 * 1024,
                },
                },
                spareBlocks: 3,
                dataIntegrityValidationCache: {
                cacheSize: 300000,
                cacheDuration: '14400s',
                cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
                },
            },
            },
        },
        replicator: { deduplicating: { 'local': {} } },
        },
    },
    },
    browserUrl: common.browserUrl,
    maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    scheduler: { address: 'scheduler:8983' },
    global: common.global + {
    setUmask: { umask: 0 },
    },
    buildDirectories: [{
    virtual: {
        maximumExecutionTimeoutCompensation: '3600s',
        shuffleDirectoryListings: true,
        maximumWritableFileUploadDelay: '60s',
        mount: {
        mountPath: '/worker/build',
        fuse: {
            directoryEntryValidity: "300s",
            inodeAttributeValidity: "300s",
            allowOther: true,
            mountMethod: 1,
        },
        },
    },
    runners: [{
        endpoint: { address: 'unix:///worker/runner' },
        concurrency: 8,
        maximumFilePoolFileCount: 20000,
        maximumFilePoolSizeBytes: 8*1024*1024*1024,
        platform: {
        properties: [
            { name: 'OSFamily', value: 'linux' },
            { name: 'container-image', value: '<image>' },
        ],
        },
        workerId: {
        'pod': std.extVar("POD_NAME"),
        'node': std.extVar("NODE_NAME")
        },
    }],
    }],
    filePool: {
    inMemory: {},
    },
    outputUploadConcurrency: 10,
    inputDownloadConcurrency: 11,
    directoryCache: {
    maximumCount: 20000,
    maximumSizeBytes: 1000 * 1000 * 1024,
    cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
    },
    prefetching: {
    fileSystemAccessCache:{
        readCaching: {
        slow: common.blobstore.contentAddressableStorage,
        fast: {
            'local': {
                keyLocationMapOnBlockDevice: {
                file: {
                    path: '/storage-worker-fsac/key_location_map',
                    sizeBytes: 100 * 1024 * 1024,
                },
                },
                keyLocationMapMaximumGetAttempts: 8,
                keyLocationMapMaximumPutAttempts: 32,
                oldBlocks: 8,
                currentBlocks: 24,
                newBlocks: 1,
                blocksOnBlockDevice: {
                    source: {
                        file: {
                        path: '/storage-worker-fsac/blocks',
                        sizeBytes: 350 * 1024 * 1024 * 1024,
                        },
                    },
                    spareBlocks: 3,
                    dataIntegrityValidationCache: {
                        cacheSize: 300000,
                        cacheDuration: '14400s',
                        cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
                    },
                },
            },
        },
        replicator: { 'local' : {} },
        },
    },
    bloomFilterBitsPerPath: 14,
    bloomFilterMaximumSizeBytes: 65536,
    },
}
```

</details>

<details>

<summary>storage </summary>

```
local common = import 'common.libsonnet';

{
  grpcServers: [{
    listenAddresses: [':8981'],
    authenticationPolicy: { allow: {} },
  }],
  maximumMessageSizeBytes: common.maximumMessageSizeBytes,
  global: common.global,
  fileSystemAccessCache: {
    backend: {
      'local': {
        keyLocationMapInMemory: {
          entries: 10 * 1000 * 1000,
        },
        keyLocationMapMaximumGetAttempts: 8,
        keyLocationMapMaximumPutAttempts: 32,
        oldBlocks: 16,
        currentBlocks: 48,
        newBlocks: 1,
        blocksOnBlockDevice: {
          source: {
            file: {
              path: '/storage/storage-fsac/blocks',
              sizeBytes: 68 * 1024 * 1024,
            },
          },
          spareBlocks: 3,
          dataIntegrityValidationCache: {
            cacheSize: 100000,
            cacheDuration: '14400s',
            cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
          },
        },
      },
    },
    getAuthorizer: { allow: {} },
    putAuthorizer: { allow: {} },
  },
  contentAddressableStorage: {
    backend: {
      'local': {
        keyLocationMapInMemory: {
          entries: 10 * 1000 * 1000,
        },
        keyLocationMapMaximumGetAttempts: 16,
        keyLocationMapMaximumPutAttempts: 64,
        oldBlocks: 8,
        currentBlocks: 24,
        newBlocks: 3,
        blocksOnBlockDevice: {
          source: {
            file: {
              path: '/storage/storage-cas/blocks',
              sizeBytes: 350 * 1024 * 1024 * 1024,
            },
          },
          spareBlocks: 3,
        },
      },
    },
    getAuthorizer: { allow: {} },
    putAuthorizer: { allow: {} },
    findMissingAuthorizer: { allow: {} },
  },
  actionCache: {
    backend: {
      'local': {
        keyLocationMapInMemory: {
          entries: 10 * 1000 * 1000,
        },
        keyLocationMapMaximumGetAttempts: 16,
        keyLocationMapMaximumPutAttempts: 64,
        oldBlocks: 8,
        currentBlocks: 24,
        newBlocks: 1,
        blocksOnBlockDevice: {
          source: {
            file: {
              path: '/storage/storage-ac/blocks',
              sizeBytes: 100 * 1024 * 1024,
            },
          },
          spareBlocks: 3,
        },
      },
    },
    getAuthorizer: { allow: {} },
    putAuthorizer: { allow: {} },
  },
}
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: buildbarn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage
  serviceName: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - args:
        - /config/storage.jsonnet
        image: ghcr.io/buildbarn/bb-storage:20241212T082716Z-078d9d7
        name: storage
        ports:
        - containerPort: 8981
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /storage
          name: fast
      initContainers:
      - name: volume-init
        image: busybox:1.31.1-uclibc
        command:
        - sh
        - -c
        - mkdir -m 0700 -p /storage/storage-cas/persistent_state /storage/storage-ac/persistent_state /storage/storage-fsac/persistent_state
        volumeMounts:
          - mountPath: /storage
            name: fast
      volumes:
      - name: configs
        configMap:
          name: buildbarn-config
          items:
          - key: common.libsonnet
            path: common.libsonnet
          - key: storage.jsonnet
            path: storage.jsonnet
  volumeClaimTemplates:
  - metadata:
      name: fast
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "fast-disks"
      resources:
        requests:
          storage: 350Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: storage
  namespace: buildbarn
spec:
  clusterIP: None
  ports:
  - port: 8981
    protocol: TCP
    name: grpc
  selector:
    app: storage
```

</details>
