### ISSUE TITLE
What configurations are needed to have a multi-runner to 1 worker setup?

### ISSUE THREAD

**Issue by Ryang20718** [buildbarn/bb-deployments#166]
Hi, I'm trying to implement the suggested multi-runner to 1 worker setup. However, I'm hitting errors along the following lines of

` Worker failed readiness check: connection error: desc = "transport: Error while dialing: dial unix /mnt/fast-disks/kube/worker/runner3: connect: no such file or directory"`

if I have multiple runners per worker, what additional modifcations do I need to ensure these sockets are created?

**Comment by Ryang20718** [comment]
<details>

<summary>worker jsonnet</summary>

```
local common = import 'common.libsonnet';

{
    blobstore: {
    actionCache: common.blobstore.actionCache,
    contentAddressableStorage: {
        readCaching: {
        slow: common.blobstore.contentAddressableStorage,
        fast: {
            'local': {
            keyLocationMapInMemory: {
                entries: 16777259,
            },
            keyLocationMapMaximumGetAttempts: 8,
            keyLocationMapMaximumPutAttempts: 32,
            oldBlocks: 8,
            currentBlocks: 24,
            newBlocks: 1,
            blocksOnBlockDevice: {
                source: {
                file: {
                path: '/mnt/fast-disks/kube/storage-worker-cas/blocks',
                sizeBytes: 350 * 1024 * 1024 * 1024,
                },
                },
                spareBlocks: 3,
                dataIntegrityValidationCache: {
                cacheSize: 300000,
                cacheDuration: '14400s',
                cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
                },
            },
            },
        },
        replicator: { deduplicating: { 'local': {} } },
        },
    },
    },
    browserUrl: common.browserUrl,
    maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    scheduler: { address: 'scheduler:8983' },
    global: common.global {
    setUmask: { umask: 0 },
    },
    buildDirectories: [{
    virtual: {
        maximumExecutionTimeoutCompensation: '3600s',
        shuffleDirectoryListings: true,
        maximumWritableFileUploadDelay: '60s',
        mount: {
        mountPath: '/mnt/fast-disks/kube/worker/build',
        fuse: {
            directoryEntryValidity: "300s",
            inodeAttributeValidity: "300s",
            allowOther: true,
            mountMethod: 'DIRECT',
        },
        },
    },
    runners: [
    {
        endpoint: { address: std.format('/mnt/fast-disks/kube/worker/runner%d', runnerIndex) },
        concurrency: 1,
        maximumFilePoolFileCount: 2 * 100000, // arbitrary
        maximumFilePoolSizeBytes: common.maximumFilePoolSizeBytes, // arbitrary
        platform: {
        properties: [
            // must be lexigraphically sorted
            { name: 'container_image', value: 'docker://<image>' },
            { name: 'gpu_count', value: '0'},
        ],
        },
        workerId: {
        pod: std.extVar("POD_NAME"),
        node: std.extVar("NODE_NAME"),
        // needed to make this unique to the scheduler
        thread: std.format('%d', runnerIndex),
        },
    } for runnerIndex in std.range(1, common.maxRunnerCount)
    ],
    }],
    filePool: {
        blockDevice: {
        file: {
            path: '/mnt/fast-disks/kube/worker/filepool',
            // concurrency * maximumFilePoolSizeBytes
            sizeBytes: std.floor(common.maximumFilePoolSizeBytes * common.maxRunnerCount),
        },
        },
    },
    outputUploadConcurrency: 10,
    inputDownloadConcurrency: 11,
    directoryCache: {
        maximumCount: 4 * 50000, // arbitrary
        maximumSizeBytes: 4 * 100 * 1024 * 1024, // arbitrary
        cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
    },
    prefetching: {
    fileSystemAccessCache:{
        readCaching: {
        slow: common.blobstore.contentAddressableStorage,
        fast: {
            'local': {
                keyLocationMapInMemory: {
                    entries: 16777259,
                },
                keyLocationMapMaximumGetAttempts: 8,
                keyLocationMapMaximumPutAttempts: 32,
                oldBlocks: 8,
                currentBlocks: 24,
                newBlocks: 1,
                blocksOnBlockDevice: {
                    source: {
                        file: {
                        path: '/mnt/fast-disks/kube/storage-worker-fsac/blocks',
                        sizeBytes: 350 * 1024 * 1024 * 1024,
                        },
                    },
                    spareBlocks: 3,
                    dataIntegrityValidationCache: {
                        cacheSize: 300000,
                        cacheDuration: '14400s',
                        cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
                    },
                },
            },
        },
        replicator: { 'local' : {} },
        },
    },
    bloomFilterBitsPerPath: 14,
    bloomFilterMaximumSizeBytes: 65536,
    },
}
```


</details>

<details>

<summary>runner jsonnet</summary>

```
local common = import 'common.libsonnet';
{
  buildDirectoryPath: '/mnt/fast-disks/kube/worker/build',
  grpcServers: [{
    listenPaths: [std.format('unix:///mnt/fast-disks/kube/worker/runner%d', runnerIndex) for runnerIndex in std.range(1, common.maxRunnerCount)],
    authenticationPolicy: { allow: {} },
  }],
}

```

</details>


<details>

<summary>worker yaml </summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ubuntu20-04
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      instance: ubuntu20-04
  template:
    metadata:
      labels:
        app: worker
        instance: ubuntu20-04
    spec:
      containers:
      - name: worker
        resources:
          limits:
            cpu: "1"
            memory: 9000Mi
          requests:
            cpu: "1"
            memory: 8000Mi
        args:
        - /config/worker-ubuntu20-04.jsonnet
        image: ghcr.io/buildbarn/bb-worker:20241215T094620Z-d03d5e3
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /mnt/fast-disks/kube/worker
          mountPropagation: Bidirectional
          name: worker
        - mountPath: /mnt/fast-disks/kube/storage-worker-cas
          name: storage-worker-cas
        - mountPath: /mnt/fast-disks/kube/storage-worker-fsac
          name: storage-worker-fsac
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: runner
        resources:
          limits:
            cpu: "1"
            memory: 12Gi
          requests:
            cpu: "1"
            memory: 11Gi
        command: [/bb/tini, -v, --, /bb/bb_runner, /config/runner-ubuntu20-04.jsonnet]
        image: <image>
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /mnt/fast-disks/kube/worker
          mountPropagation: HostToContainer
          name: worker
        - mountPath: /mnt/fast-disks/kube/storage-worker-cas
          name: storage-worker-cas
        - mountPath: /mnt/fast-disks/kube/storage-worker-fsac
          name: storage-worker-fsac
        - mountPath: /dev/shm
          name: shared-memory
        - mountPath: /bb
          name: empty
          readOnly: true
        securityContext:
          runAsUser: 65534
          allowPrivilegeEscalation: false
      initContainers:
      - name: bb-runner-installer
        image: ghcr.io/buildbarn/bb-runner-installer:20241215T094620Z-d03d5e3
        volumeMounts:
        - mountPath: /bb
          name: empty
      - name: volume-init
        image: busybox:1.31.1-uclibc
        command:
        - sh
        - -c
        - set -x; mkdir -pm 0777 /mnt/fast-disks/kube/worker/build && mkdir -pm 0700 /mnt/fast-disks/kube/worker/cache && mkdir -pm 0777 /mnt/fast-disks/kube/storage-worker-cas && mkdir -pm 0777 /mnt/fast-disks/kube/storage-worker-fsac && chmod 0777 /mnt/fast-disks/kube/worker
        volumeMounts:
        - mountPath: /mnt/fast-disks/kube/worker
          name: worker
        - mountPath: /mnt/fast-disks/kube/storage-worker-cas
          name: storage-worker-cas
        - mountPath: /mnt/fast-disks/kube/storage-worker-fsac
          name: storage-worker-fsac
      volumes:
      - name: empty
        hostPath:
          path: /mnt/fast-disks/kube
      - name: configs
        configMap:
          name: buildbarn-config
          items:
          - key: common.libsonnet
            path: common.libsonnet
          - key: runner-ubuntu20-04.jsonnet
            path: runner-ubuntu20-04.jsonnet
          - key: worker-ubuntu20-04.jsonnet
            path: worker-ubuntu20-04.jsonnet
      - name: worker
        hostPath:
          path: /mnt/fast-disks/kube/worker
      - name: storage-worker-cas
        hostPath:
          path: /mnt/fast-disks/kube/storage-worker-cas
      - name: storage-worker-fsac
        hostPath:
          path: /mnt/fast-disks/kube/storage-worker-fsac
      - name: shared-memory
        hostPath:
          path: /dev/shm
```

</details>
