### ISSUE TITLE
Buildbarn deployment for Kubernetes is incomplete

### ISSUE THREAD

**Issue by MikhailTymchukFT** [buildbarn/bb-deployments#37]
I deployed Buildbarn to Kubernetes engine, but there are some issues:
1. There is an error saying
```
error while evaluating the ingress spec: service "buildbarn/browser" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
```
<img width="938" alt="Screenshot 2020-07-10 at 19 31 08" src="https://user-images.githubusercontent.com/62020066/87177666-b26c5e80-c2e4-11ea-84fd-157b11674cc4.png">

   Looks like [`bb-browser.example.com`](https://github.com/buildbarn/bb-deployments/blob/master/kubernetes/browser.yaml#L67) is a placeholder, but [the readme](https://github.com/buildbarn/bb-deployments/blob/master/kubernetes/README.md) does not mention that.

2. What is the client config for k8s remote execution service? [.bazelrc for docker-compose](https://github.com/buildbarn/bb-deployments#remote-execution) is no longer applicable.

**Comment by samschlegel** [comment]
1. This is a GKE specific error, as not all Ingress require NodePort or LoadBalancer. On GKE if you have your cluster setup as VPC-native, you can also solve this by adding and annotation to create a NEG. https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#create_service

2. It should just work by changing localhost to the IP you have configured for the frontend LoadBalancer

**Comment by MikhailTymchukFT** [comment]
Thanks @samschlegel!

Almost worked. I updated my `browser.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: buildbarn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - image: buildbarn/bb-browser:20200514T172056Z-1c2932b
        args:
        - /config/browser.jsonnet
        name: browser
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: browser
              items:
              - key: browser.jsonnet
                path: browser.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
    cloud.google.com/neg: '{"ingress": true }'
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: browser
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser
  namespace: buildbarn
spec:
  backend:
    serviceName: browser
    servicePort: 80
```

All services are up:
<img width="738" alt="Screenshot 2020-07-15 at 00 33 58" src="https://user-images.githubusercontent.com/62020066/87478740-f340dc00-c632-11ea-9985-251a0147db23.png">

Set up my `.bazelrc`:
```
build --remote_executor=grpc://<frontend ip>:8980
build --remote_instance_name=remote-execution
```

And invoked remote build for a sample repo:
```
$ bazel build '...'
INFO: Invocation ID: 2d339671-8808-48ea-a7d6-d084aa8e1bf6
INFO: Analyzed 7 targets (23 packages loaded, 585 targets configured).
INFO: Found 7 targets...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_mikhailtymchuk/ea3ea5978046d077099083e425031a09/sandbox
ERROR: /Users/mikhailtymchuk/repos/java/genrules/BUILD:5:1: Executing genrule //genrules:step1 failed (Exit 34). Note: Remote connection/protocol failed with: execution failed FAILED_PRECONDITION: No workers exist for instance "remote-execution" platform {}
INFO: Elapsed time: 18.060s, Critical Path: 1.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

What am I missing now?
